import { randomUUID } from "node:crypto";
import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import {
  createIsolatedSandboxProvider,
  type ExecResult,
  type IsolatedSandboxHandle,
  type IsolatedSandboxProvider,
} from "@ai-hero/sandcastle";
import {
  runProcess,
  type ProcessRunner,
  type ProcessRunOptions,
} from "../process.js";

const DEFAULT_WORKTREE_PATH = "/home/exedev/yogi-workspace";
const ENV_FILE_PATH = "/home/exedev/.yogi-env";
const SAFE_ENV_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/;
const SAFE_VM_NAME = /^[a-z][a-z0-9-]{1,46}[a-z0-9]$/;

export interface ExeOptions {
  /** Exact VM name. A unique `yogi-*` name is generated when omitted. */
  readonly name?: string;
  /** OCI image understood by exe.dev, such as `ubuntu:24.04`. */
  readonly image?: string;
  readonly cpu?: number;
  /** Memory using exe.dev units, such as `8GB`. */
  readonly memory?: string;
  /** Disk size using exe.dev units, such as `30GB`. */
  readonly disk?: string;
  readonly region?: string;
  readonly tags?: readonly string[];
  readonly setupScript?: string;
  /** Provider-level environment merged with agent and run environment. */
  readonly env?: Record<string, string>;
  /** Keep the VM after the sandbox closes. Defaults to false. */
  readonly persist?: boolean;
  /** Override the repository path inside the VM. */
  readonly worktreePath?: string;
  /** SSH executable. */
  readonly sshCommand?: string;
  /** SCP executable. */
  readonly scpCommand?: string;
  /**
   * Process adapter for tests and embedded runtimes.
   * @internal
   */
  readonly processRunner?: ProcessRunner;
}

const shellQuote = (value: string): string =>
  `'${value.replaceAll("'", "'\"'\"'")}'`;

const createVmName = (): string =>
  `yogi-${Date.now().toString(36)}-${randomUUID().slice(0, 8)}`;

const assertVmName = (name: string): void => {
  if (!SAFE_VM_NAME.test(name)) {
    throw new Error(
      "exe.dev VM names must be 3-48 lowercase letters, numbers, or hyphens and start with a letter",
    );
  }
};

const serializeEnvironment = (env: Record<string, string>): string => {
  const lines = ["# Generated by Yogi. Do not commit this file."];

  for (const [name, value] of Object.entries(env)) {
    if (!SAFE_ENV_NAME.test(name)) {
      throw new Error(`Invalid environment variable name: ${name}`);
    }
    if (value.includes("\0")) {
      throw new Error(`Environment variable ${name} contains a null byte`);
    }
    lines.push(`export ${name}=${shellQuote(value)}`);
  }

  return `${lines.join("\n")}\n`;
};

const assertSucceeded = (result: ExecResult, action: string): void => {
  if (result.exitCode !== 0) {
    const detail = result.stderr.trim() || result.stdout.trim();
    throw new Error(`${action} failed (exit ${result.exitCode}): ${detail}`);
  }
};

const createArguments = (name: string, options: ExeOptions): string[] => {
  const args = ["exe.dev", "new", `--name=${name}`, "--json"];

  if (options.image) args.push(`--image=${options.image}`);
  if (options.cpu !== undefined) args.push(`--cpu=${options.cpu}`);
  if (options.memory) args.push(`--memory=${options.memory}`);
  if (options.disk) args.push(`--disk=${options.disk}`);
  if (options.region) args.push(`--region=${options.region}`);
  if (options.setupScript) args.push(`--setup-script=${options.setupScript}`);
  for (const tag of options.tags ?? ["yogi"]) args.push(`--tag=${tag}`);

  return args;
};

const remoteCommand = (command: string, cwd: string, sudo: boolean): string => {
  const withDirectory = `cd ${shellQuote(cwd)} && ${command}`;
  return sudo
    ? `sudo sh -lc ${shellQuote(withDirectory)}`
    : `sh -lc ${shellQuote(withDirectory)}`;
};

/**
 * Create an isolated Sandcastle provider backed by an exe.dev VM.
 *
 * A new VM is created per handle and removed on close unless `persist` is true.
 * Authentication is delegated to the user's existing SSH configuration.
 */
export const exe = (options: ExeOptions = {}): IsolatedSandboxProvider =>
  createIsolatedSandboxProvider({
    name: "exe.dev",
    ...(options.env ? { env: options.env } : {}),
    create: async (createOptions): Promise<IsolatedSandboxHandle> => {
      const runner = options.processRunner ?? runProcess;
      const ssh = options.sshCommand ?? "ssh";
      const scp = options.scpCommand ?? "scp";
      const vmName = options.name ?? createVmName();
      const sshTarget = `${vmName}.exe.xyz`;
      const worktreePath = options.worktreePath ?? DEFAULT_WORKTREE_PATH;

      assertVmName(vmName);

      const created = await runner(ssh, createArguments(vmName, options));
      assertSucceeded(created, `Creating exe.dev VM ${vmName}`);

      let closed = false;

      const removeVm = async (): Promise<void> => {
        if (closed || options.persist) return;
        closed = true;
        const removed = await runner(ssh, ["exe.dev", "rm", vmName, "--json"]);
        assertSucceeded(removed, `Removing exe.dev VM ${vmName}`);
      };

      try {
        const environment = serializeEnvironment(createOptions.env);
        const prepared = await runner(
          ssh,
          [
            sshTarget,
            `umask 077; cat > ${shellQuote(ENV_FILE_PATH)}; mkdir -p ${shellQuote(worktreePath)}`,
          ],
          { stdin: environment },
        );
        assertSucceeded(prepared, `Preparing exe.dev VM ${vmName}`);
      } catch (error) {
        await removeVm().catch(() => undefined);
        throw error;
      }

      return {
        worktreePath,

        exec: async (
          command: string,
          execOptions?: {
            onLine?: (line: string) => void;
            cwd?: string;
            sudo?: boolean;
            stdin?: string;
          },
        ): Promise<ExecResult> => {
          const commandWithEnvironment = `. ${shellQuote(ENV_FILE_PATH)}; ${command}`;
          const processOptions: ProcessRunOptions = {};
          if (execOptions?.stdin !== undefined) {
            Object.assign(processOptions, { stdin: execOptions.stdin });
          }
          if (execOptions?.onLine) {
            Object.assign(processOptions, {
              onStdoutLine: execOptions.onLine,
            });
          }

          return runner(
            ssh,
            [
              sshTarget,
              remoteCommand(
                commandWithEnvironment,
                execOptions?.cwd ?? worktreePath,
                execOptions?.sudo ?? false,
              ),
            ],
            processOptions,
          );
        },

        copyIn: async (
          hostPath: string,
          sandboxPath: string,
        ): Promise<void> => {
          const directoryReady = await runner(ssh, [
            sshTarget,
            `mkdir -p ${shellQuote(dirname(sandboxPath))}`,
          ]);
          assertSucceeded(directoryReady, "Preparing remote copy destination");

          const copied = await runner(scp, [
            "-r",
            hostPath,
            `${sshTarget}:${shellQuote(sandboxPath)}`,
          ]);
          assertSucceeded(copied, `Copying ${hostPath} into exe.dev`);
        },

        copyFileOut: async (
          sandboxPath: string,
          hostPath: string,
        ): Promise<void> => {
          await mkdir(dirname(hostPath), { recursive: true });
          const copied = await runner(scp, [
            `${sshTarget}:${shellQuote(sandboxPath)}`,
            hostPath,
          ]);
          assertSucceeded(copied, `Copying ${sandboxPath} out of exe.dev`);
        },

        close: removeVm,
      };
    },
  });
